version: '3.8'
services:
  aurras-event-feed-eth:
    platform: linux/amd64
    image: hugobyte/eth-event-feed:v0.1
    container_name: aurras-event-feed-eth
    restart: always
    networks:
      - gateway
    external_links:
      - kafka:kafka.docker
      - apigateway:apigateway.docker
    env_file:
      - ./local.env
    volumes:
      - ./logs:/logs
      - ./config:/app/config

networks:
  default:
    name: aurras
    driver: bridge
  gateway:
    name: gateway
    external: true